project:
  type: website

website:
  title: "Bruno's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Shinoa12
      - icon: linkedin
        href: https://linkedin.com/in/bruno-delrio
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css



